<%-- 
    Document   : customer
    Created on : 4 Nov, 2020, 11:01:18 PM
    Author     : utkarsh
--%>

<%@page import="javax.print.attribute.standard.Copies"%>
<%@page import="javax.print.attribute.PrintRequestAttributeSet"%>
<%@page import="javax.print.attribute.HashPrintRequestAttributeSet"%>
<%@page import="javax.print.SimpleDoc"%>
<%@page import="javax.print.DocFlavor"%>
<%@page import="javax.print.Doc"%>
<%@page import="java.io.FileInputStream"%>
<%@page import="javax.print.event.PrintJobEvent"%>
<%@page import="javax.print.event.PrintJobAdapter"%>
<%@page import="javax.print.DocPrintJob"%>
<%@page import="javax.print.PrintServiceLookup"%>
<%@page import="javax.print.PrintService"%>
<%@page import="com.twilio.rest.api.v2010.account.Message"%>
<%@page import="com.twilio.type.PhoneNumber"%>
<%@page import="com.twilio.Twilio"%>
<%@page import="shoopingcart.CartItemBean"%>
<%@page import="shoopingcart.CartBean"%>
<%@page import="java.util.Date"%>
<%@page import="com.itextpdf.text.pdf.PdfPTable"%>
<%@page import="com.itextpdf.text.Element"%>
<%@page import="com.itextpdf.text.pdf.PdfPCell"%>
<%@page import="com.itextpdf.text.Phrase"%>
<%@page import="com.itextpdf.text.Section"%>
<%@page import="com.itextpdf.text.Chapter"%>
<%@page import="com.itextpdf.text.Anchor"%>
<%@page import="com.itextpdf.text.Paragraph"%>
<%@page import="java.io.FileOutputStream"%>
<%@page import="com.itextpdf.text.pdf.PdfWriter"%>
<%@page import="com.itextpdf.text.Document"%>
<%@page import="com.itextpdf.text.Font"%>
<%@page import="java.sql.DriverManager"%>
<%@page import="java.sql.PreparedStatement"%>
<%@page import="java.sql.Connection"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %> 
<!DOCTYPE html>



 <%
     
     
     
     CartBean cb =new CartBean();
     CartItemBean cib=new CartItemBean();
     
    
      String FILE = "FirstPdf.pdf";
      Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
     
      Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
      Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
       String t=request.getParameter("cid");
       String p=request.getParameter("name");
       String q=request.getParameter("num");
       String r=request.getParameter("email");
       String f=request.getParameter("ftotal");
       String s = request.getParameter("status");
       
       Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/smbs","root","1234");
       PreparedStatement ps=con.prepareStatement("insert into sales values(?,?,?,?,?,?)");
       
       ps.setString(1, p);
       ps.setString(2, q);
       ps.setString(3, r);   
        ps.setString(4, f);
        ps.setString(5, s);
        ps.setString(6, t);
    int i =ps.executeUpdate();
    if(i>0){
        out.println("data inserted");
        
      Twilio.init("AC59627eb05c9665db59e9216781fe7789","44be4323f8f25bb33833a508cb176ce5");
Message message = Message.creator(
    new PhoneNumber("+91"+q),
    new PhoneNumber("+13342139136"),
    "Dear "+p+", Your Total amount is "+f+" and Your amount has been "+s)
.create();

 RequestDispatcher rd=request.getRequestDispatcher("ShoppingCart.jsp");
                 rd.forward(request, response);

 Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
        document.addTitle("SUOERMARKET BILLING INVOICE");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("UTKARSH BAFNA");
        document.addCreator("Lars Vogel");
        
        Paragraph preface = new Paragraph();
        // We add one empty line
        // Lets write a big header
        preface.add(new Paragraph("ORDER INVOICE", catFont));

        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + "UTKARSH BAFNA" + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
       

        document.add(preface);
        // Start a new page
        document.newPage();
       

        
        
        PdfPTable table = new PdfPTable(2);
        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);
        
       
        PdfPCell custDetails = new PdfPCell(new Phrase("Customer Details"));
        custDetails.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(custDetails);


        custDetails = new PdfPCell(new Phrase("Bafna Enterprises"));
        custDetails.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(custDetails);

      
        table.setHeaderRows(1);

        table.addCell("Customer Name:");
        table.addCell(p);
        table.addCell("Mob No.");
        table.addCell(q);
        table.addCell("Email");
        table.addCell(r);
        table.addCell("Total");
        table.addCell(f);
        
        document.add(table);
       


        PdfPTable carttable = new PdfPTable(5);
        PdfPCell cartDetails = new PdfPCell(new Phrase("Product Details"));
        cartDetails.setHorizontalAlignment(Element.ALIGN_CENTER);
        carttable.addCell(cartDetails); 
        
        
        cartDetails = new PdfPCell(new Phrase("Bafna Enterprises"));
        cartDetails.setHorizontalAlignment(Element.ALIGN_CENTER);
        carttable.addCell(cartDetails);
        
        cartDetails = new PdfPCell(new Phrase("Bafna Enterprises"));
        cartDetails.setHorizontalAlignment(Element.ALIGN_CENTER);
        carttable.addCell(cartDetails);
        
        cartDetails = new PdfPCell(new Phrase("Bafna Enterprises"));
        cartDetails.setHorizontalAlignment(Element.ALIGN_CENTER);
        carttable.addCell(cartDetails);
        
        cartDetails = new PdfPCell(new Phrase("Bafna Enterprises"));
        cartDetails.setHorizontalAlignment(Element.ALIGN_CENTER);
        carttable.addCell(cartDetails);
        
        carttable.setHeaderRows(1);

        
for(int j=0; j<cb.getLineItemCount();j++ )
{
   carttable.addCell(cib.getPartNumber());
    carttable.addCell(cib.getModelDescription());
     carttable.addCell(""+cib.getQuantity());
      carttable.addCell(""+cib.getUnitCost());
       carttable.addCell(""+cib.getTotalCost());
        
}
        
      
        
       document.add(carttable);
        
        document.close();

        
        
    }else{
        out.println("not inserted");
    }

    
  %>
  
  
